In [1]:
m = 10
n = 3

3

In [2]:
using Matching
function mat2vecs{T<:Integer}(prefs::Matrix{T})
    return [prefs[1:findfirst(prefs[:, j], 0)-1, j] for j in 1:size(prefs, 2)]
end
m_prefs, f_prefs = mat2vecs.(random_prefs(m, n, allow_unmatched=false))
m_prefs, f_prefs = mat2vecs.(random_prefs(m, n))

(Array{Int64,1}[[1],[3,1,2],[2,1,3],[1],[3,2,1],[1],[3,1],[1,2],[3],[3,1,2]],Array{Int64,1}[[4],[5,3,6,9,7],[9,2,4,7,5]])

In [3]:
f_prefs

3-element Array{Array{Int64,1},1}:
 [4]        
 [5,3,6,9,7]
 [9,2,4,7,5]

In [4]:
m_prefs

10-element Array{Array{Int64,1},1}:
 [1]    
 [3,1,2]
 [2,1,3]
 [1]    
 [3,2,1]
 [1]    
 [3,1]  
 [1,2]  
 [3]    
 [3,1,2]

In [11]:
findfirst(f_prefs[m_prefs[3][1]],3) 

2

In [12]:
findfirst(f_prefs[m_prefs[4][1]],2)

0

In [5]:
function matching(m_prefs,f_prefs)
    
    for o in 1:m
        push!(m_prefs[o],0)
    end

    for k in 1:n
        push!(f_prefs[k],0)
    end
    matched_m = zeros(Int64,m)
    matched_f = zeros(Int64,n)
    accepted_m = zeros(Int64,m)         #男性iの受け入れ先が決まったらaccepted_m[1]=1
    
    while sum(accepted_m) !== m       #男性が全員受け入れ先が決まるまで
        
        for i in 1:m
            
            if m_prefs[i][1] == 0       #男性iの第一志望が独身のとき
                
                accepted_m[i] = 1       #男性iは受け入れ済みに
                
            end
            
            if m_prefs[i][1] !== 0      #男性gに第一志望の女性がいるとき
                
                if findfirst(f_prefs[m_prefs[i][1]],i) == 0       #男性iが第一志望の女性の眼中にないとき
                    
                    shift!(m_prefs[i]) #男性iの志望から第一志望を除く
                    
                end
                
                if findfirst(f_prefs[m_prefs[i][1]],i) !== 0      #男性gが第一志望の女性の選択肢に入っているとき
                    
                    if matched_f[m_prefs[i][1]] == 0        #第一志望の女性が誰も受け入れていないとき
                        
                        matched_m[i] = m_prefs[i][1]
                        matched_f[m_prefs[i][1]] = i
                        accepted_m[i] = 1　　　　　　　　　#男性iは受け入れ済みに
                        
                    end
                    
                    if matched_f[m_prefs[i][1]] !== 0        #第一志望の女性が誰かを受け入れているとき
                        
                        if findfirst(f_prefs[m_prefs[i][1]],i) < findfirst(f_prefs[m_prefs[i][1]],matched_f[m_prefs[i][1]])
                                 #男性iが保留されていた男性よりも女性の好ましい選択であるとき
                            
                                accepted_m[matched_f[m_prefs[i][1]]] = 0      #保留されていた男性を受け入れ済みから除く
                                shift!(m_prefs[matched_f[m_prefs[i][1]]]) 　　#保留されていた男性の志望から第一志望を除く
                                matched_m[matched_f[m_prefs[i][1]]] =　0 
                            
                                matched_m[i] = m_prefs[i][1]
                                matched_f[m_prefs[i][1]] = i
                                accepted_m[i] = 1               #男性iは受け入れ済みに
                            
                        end
                         
                        if findfirst(f_prefs[m_prefs[i][1]],i) > findfirst(f_prefs[m_prefs[i][1]],matched_f[m_prefs[i][1]]) 
                                #保留されていた男性が男性iよりも女性の好ましい選択であるとき
                                
                                shift!(m_prefs[i])       #男性iの志望から第一志望を除く
                                
                        end
                            
                    end
                        
                end
                    
             end
                
        end
            
    end
        
    return matched_m,matched_f
        
end
                                
                                
                                
                    
                    
                        
                    
                        

matching (generic function with 1 method)

In [6]:
matching(m_prefs,f_prefs)

LoadError: BoundsError: attempt to access 3-element Array{Array{Int64,1},1} at index [0]

In [7]:
Pkg.test("MyMatching")

INFO: Testing MyMatching
=============================[ ERROR: MyMatching ]==============================

failed process: Process(`'C:\Users\Masashi Takahashi\AppData\Local\Julia-0.5.1\bin\julia' -Cx86-64 '-JC:\Users\Masashi Takahashi\AppData\Local\Julia-0.5.1\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'C:\Users\Masashi Takahashi\.julia\v0.5\MyMatching\test\runtests.jl'`, ProcessExited(1)) [1]



LoadError: MyMatching had test errors

In [8]:
? findfirst

search: findfirst



```
findfirst(A)
```

Return the linear index of the first non-zero value in `A` (determined by `A[i]!=0`). Returns `0` if no such value is found.

```jldoctest
julia> A = [0 0; 1 0]
2×2 Array{Int64,2}:
 0  0
 1  0

julia> findfirst(A)
2
```

```
findfirst(A, v)
```

Return the linear index of the first element equal to `v` in `A`. Returns `0` if `v` is not found.

```jldoctest
julia> A = [4 6; 2 2]
2×2 Array{Int64,2}:
 4  6
 2  2

julia> findfirst(A,2)
2

julia> findfirst(A,3)
0
```

```
findfirst(predicate::Function, A)
```

Return the linear index of the first element of `A` for which `predicate` returns `true`. Returns `0` if there is no such element.

```jldoctest
julia> A = [1 4; 2 2]
2×2 Array{Int64,2}:
 1  4
 2  2

julia> findfirst(iseven, A)
2

julia> findfirst(x -> x>10, A)
0
```
