受入保留 (Deferred Acceptance) アルゴリズムを実装してみる。

In [1]:
m = 4
n = 3

3

In [2]:
M = [i for i in 1:m]
F = [j for j in 1:n]

3-element Array{Int64,1}:
 1
 2
 3

In [3]:
using Matching

In [4]:
function mat2vecs{T<:Integer}(prefs::Matrix{T})
    return [prefs[1:findfirst(prefs[:, j], 0)-1, j] for j in 1:size(prefs, 2)]
end

mat2vecs (generic function with 1 method)

In [5]:
m_prefs, f_prefs = mat2vecs.(random_prefs(m, n, allow_unmatched=false))

(Array{Int64,1}[[1,2,3],[3,2,1],[3,1,2],[2,1,3]],Array{Int64,1}[[4,2,3,1],[2,3,1,4],[2,4,1,3]])

In [6]:
m_prefs, f_prefs = mat2vecs.(random_prefs(m, n))

(Array{Int64,1}[[2],[3,2,1],[2],[1]],Array{Int64,1}[[2,4,3],[4,1,2,3],[1]])

In [7]:
m_prefs

4-element Array{Array{Int64,1},1}:
 [2]    
 [3,2,1]
 [2]    
 [1]    

In [8]:
f_prefs

3-element Array{Array{Int64,1},1}:
 [2,4,3]  
 [4,1,2,3]
 [1]      

In [9]:
S = zeros(m,n)　#受け入れ保留する組み合わせを0.0 -> 1.0とする　（unmatched がなければ rank(s)=n ??)

4×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [10]:
S

4×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [11]:
S[2,2]

0.0

In [12]:
S[:,1] == zeros(m)

true

In [13]:
S[1,:] == zeros(n)

true

In [14]:
zeros(m)

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

In [15]:
function matching (m_prefs, f_prefs)
    
    S = zeros(m,n)  B = []
    
    for i in 1:m
    
        if m_prefs[i] == B     #男性の好む女性がいない（いなくなった）とき
        
            return m_matched[i] = 0
        
        end
    
        if m_prefs[i] !== B　　#男性の志望する女性がいるとき
        
        
            if S[:,m_prefs[i]] == zeros(m)   #女性のとこに誰もいなければ
      
                return S[i,m_prefs[i]] = 1.0　
        
            end
    
            if S[:,m_prefs[i]] !== zeros(m)　　#女性のところに誰かいれば（受け入れ保留されている）
        
            
                
                if                                           #iのほうが女性の志望度が高いとき
                    
                end
                
                if                                           #iのほうが女性の志望度が低いとき
                    
                end
                
            end
            
        end
        
    end
        
        

LoadError: syntax: space before "(" not allowed in "matching ("

In [16]:
? findfirst

search: findfirst



```
findfirst(A)
```

Return the linear index of the first non-zero value in `A` (determined by `A[i]!=0`). Returns `0` if no such value is found.

```jldoctest
julia> A = [0 0; 1 0]
2×2 Array{Int64,2}:
 0  0
 1  0

julia> findfirst(A)
2
```

```
findfirst(A, v)
```

Return the linear index of the first element equal to `v` in `A`. Returns `0` if `v` is not found.

```jldoctest
julia> A = [4 6; 2 2]
2×2 Array{Int64,2}:
 4  6
 2  2

julia> findfirst(A,2)
2

julia> findfirst(A,3)
0
```

```
findfirst(predicate::Function, A)
```

Return the linear index of the first element of `A` for which `predicate` returns `true`. Returns `0` if there is no such element.

```jldoctest
julia> A = [1 4; 2 2]
2×2 Array{Int64,2}:
 1  4
 2  2

julia> findfirst(iseven, A)
2

julia> findfirst(x -> x>10, A)
0
```


In [17]:
? replace 

search: replace redisplay



```
replace(string, pat, r[, n])
```

Search for the given pattern `pat`, and replace each occurrence with `r`. If `n` is provided, replace at most `n` occurrences. As with search, the second argument may be a single character, a vector or a set of characters, a string, or a regular expression. If `r` is a function, each occurrence is replaced with `r(s)` where `s` is the matched substring. If `pat` is a regular expression and `r` is a `SubstitutionString`, then capture group references in `r` are replaced with the corresponding matched text.


In [18]:
ff = [[1,2,3],[2],[3,1,2]]

3-element Array{Array{Int64,1},1}:
 [1,2,3]
 [2]    
 [3,1,2]

In [19]:
findfirst(ff)

1

In [20]:
findfirst(ff[2])

1

In [21]:
findfirst(ff[3])

1

In [28]:
function matching(m_prefs, f_prefs)
    
    S = zeros(m,n)  
    B =[]
    
    for i in 1:m
    
    return replace(S[i,m_prefs[i][1]],1.0)
        
    end
    
end

matching (generic function with 1 method)

matching(Any, Any) in module Main at In[25]:3 overwritten at In[28]:3.


In [27]:
matching(m_prefs,f_prefs)

LoadError: MethodError: no method matching replace(::Float64, ::Float64)
Closest candidates are:
  replace(::String, ::Any, ::Any, ::Integer) at strings/util.jl:181
  replace(::AbstractString, ::Any, ::Any) at strings/util.jl:211
  replace(::AbstractString, ::Any, ::Any, ::Integer) at strings/util.jl:210

In [30]:
? Set

search: Set setenv setdiff setdiff! setfield! setindex! setrounding setprecision



```
Set([itr])
```

Construct a [`Set`](:obj:`Set`) of the values generated by the given iterable object, or an empty set. Should be used instead of [`IntSet`](:obj:`IntSet`) for sparse integer sets, or for sets of arbitrary objects.
