受入保留 (Deferred Acceptance) アルゴリズムを実装してみる。

In [1]:
m = 4
n = 3

3

In [2]:
M = [i for i in 1:m]
F = [j for j in 1:n]

3-element Array{Int64,1}:
 1
 2
 3

In [3]:
using Matching

In [4]:
function mat2vecs{T<:Integer}(prefs::Matrix{T})
    return [prefs[1:findfirst(prefs[:, j], 0)-1, j] for j in 1:size(prefs, 2)]
end

mat2vecs (generic function with 1 method)

In [5]:
m_prefs, f_prefs = mat2vecs.(random_prefs(m, n, allow_unmatched=false))

(Array{Int64,1}[[1,2,3],[3,2,1],[3,1,2],[2,1,3]],Array{Int64,1}[[4,2,3,1],[2,3,1,4],[2,4,1,3]])

In [6]:
m_prefs, f_prefs = mat2vecs.(random_prefs(m, n))

(Array{Int64,1}[[2],[3,2,1],[2],[1]],Array{Int64,1}[[2,4,3],[4,1,2,3],[1]])

In [7]:
m_prefs

4-element Array{Array{Int64,1},1}:
 [2]    
 [3,2,1]
 [2]    
 [1]    

In [8]:
f_prefs

3-element Array{Array{Int64,1},1}:
 [2,4,3]  
 [4,1,2,3]
 [1]      

In [9]:
S = zeros(m,n)　#受け入れ保留する組み合わせを0.0 -> 1.0とする　（unmatched がなければ rank(s)=n ??)

4×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [10]:
S

4×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [11]:
S[2,2]

0.0

In [12]:
S[:,1] == zeros(m)

true

In [13]:
S[1,:] == zeros(n)

true

In [14]:
zeros(m)

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

In [17]:
? replace 

search: replace redisplay



```
replace(string, pat, r[, n])
```

Search for the given pattern `pat`, and replace each occurrence with `r`. If `n` is provided, replace at most `n` occurrences. As with search, the second argument may be a single character, a vector or a set of characters, a string, or a regular expression. If `r` is a function, each occurrence is replaced with `r(s)` where `s` is the matched substring. If `pat` is a regular expression and `r` is a `SubstitutionString`, then capture group references in `r` are replaced with the corresponding matched text.


In [18]:
ff = [[1,2,3],[2],[3,1,2]]

3-element Array{Array{Int64,1},1}:
 [1,2,3]
 [2]    
 [3,1,2]

In [19]:
findfirst(ff)

1

In [20]:
findfirst(ff[2])

1

In [21]:
findfirst(ff[3])

1

In [28]:
function matching(m_prefs, f_prefs)
    
    S = zeros(m,n)  
    B =[]
    
    for i in 1:m
    
    return replace(S[i,m_prefs[i][1]],1.0)
        
    end
    
end

matching (generic function with 1 method)

matching(Any, Any) in module Main at In[25]:3 overwritten at In[28]:3.


In [27]:
matching(m_prefs,f_prefs)

LoadError: MethodError: no method matching replace(::Float64, ::Float64)
Closest candidates are:
  replace(::String, ::Any, ::Any, ::Integer) at strings/util.jl:181
  replace(::AbstractString, ::Any, ::Any) at strings/util.jl:211
  replace(::AbstractString, ::Any, ::Any, ::Integer) at strings/util.jl:210

In [30]:
? Set

search: Set setenv setdiff setdiff! setfield! setindex! setrounding setprecision



```
Set([itr])
```

Construct a [`Set`](:obj:`Set`) of the values generated by the given iterable object, or an empty set. Should be used instead of [`IntSet`](:obj:`IntSet`) for sparse integer sets, or for sets of arbitrary objects.


In [1]:
zeros(0)

0-element Array{Float64,1}

In [2]:
?findfirst

search: findfirst



```
findfirst(A)
```

Return the linear index of the first non-zero value in `A` (determined by `A[i]!=0`). Returns `0` if no such value is found.

```jldoctest
julia> A = [0 0; 1 0]
2×2 Array{Int64,2}:
 0  0
 1  0

julia> findfirst(A)
2
```

```
findfirst(A, v)
```

Return the linear index of the first element equal to `v` in `A`. Returns `0` if `v` is not found.

```jldoctest
julia> A = [4 6; 2 2]
2×2 Array{Int64,2}:
 4  6
 2  2

julia> findfirst(A,2)
2

julia> findfirst(A,3)
0
```

```
findfirst(predicate::Function, A)
```

Return the linear index of the first element of `A` for which `predicate` returns `true`. Returns `0` if there is no such element.

```jldoctest
julia> A = [1 4; 2 2]
2×2 Array{Int64,2}:
 1  4
 2  2

julia> findfirst(iseven, A)
2

julia> findfirst(x -> x>10, A)
0
```


In [7]:
z =[1 0 0 ;0 1 0; 1 0 0]

3×3 Array{Int64,2}:
 1  0  0
 0  1  0
 1  0  0

In [10]:
sum(z[:,2])

1

In [13]:
sum(z[:,1])

2

In [18]:
x = zeros(3,3)

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [22]:
x[2,2] = 1.0
x[3,1] = 1.0

1.0

In [23]:
x

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  1.0  0.0
 1.0  0.0  0.0

In [24]:
sum(x[:,1])

1.0

In [26]:
a = [1,2,3,4,5]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [28]:
shift!(a)

1

In [29]:
a

4-element Array{Int64,1}:
 2
 3
 4
 5

In [30]:
x

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  1.0  0.0
 1.0  0.0  0.0

In [33]:
size(x[:,1],1)

3

In [34]:
size(x[3,:],1)

3

In [35]:
? size

search: size sizeof sizehint! Csize_t resize! filesize Cssize_t trailingsize



```
size(A::AbstractArray, [dim...])
```

Returns a tuple containing the dimensions of `A`. Optionally you can specify the dimension(s) you want the length of, and get the length of that dimension, or a tuple of the lengths of dimensions you asked for.

```jldoctest
julia> A = ones(2,3,4);

julia> size(A, 2)
3

julia> size(A,3,2)
(4,3)
```


In [37]:
A = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [40]:
zeros(0)

0-element Array{Float64,1}

In [46]:
m = 4
n = 3

3

In [47]:
M = [i for i in 1:m]
    F = [j for j in 1:n]
    matched_m = zeros(m) 
    matched_f = zeros(n)
    accepted_m = zeros(0)
    

0-element Array{Float64,1}

In [52]:
for i in 1:m
push!(accepted_m,i)
end

In [53]:
accepted_m

9-element Array{Float64,1}:
 1.0
 1.0
 2.0
 3.0
 4.0
 1.0
 2.0
 3.0
 4.0

In [54]:
sum(accepted_m)

21.0

In [55]:
ones(2)

2-element Array{Float64,1}:
 1.0
 1.0

In [56]:
t = [0i for i in 1:m]

4-element Array{Int64,1}:
 0
 0
 0
 0

In [60]:
y = [1]

1-element Array{Int64,1}:
 1

In [61]:
pop!(y)

1

In [62]:
y

0-element Array{Int64,1}

In [63]:
y = [1,6,3,4,2,3,0]

7-element Array{Int64,1}:
 1
 6
 3
 4
 2
 3
 0

In [71]:
-findfirst(y,2)-findfirst(y,7)

true

In [74]:
si = [0w for w in 1:m]

4-element Array{Int64,1}:
 0
 0
 0
 0

In [80]:
nu = [0r for r in 1:n]

LoadError: syntax: invalid comprehension syntax

4×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [83]:
zeros(Int64,m,n)

4×3 Array{Int64,2}:
 0  0  0
 0  0  0
 0  0  0
 0  0  0

In [84]:
m =[0]

1-element Array{Int64,1}:
 0

In [85]:
push!(m,1)

2-element Array{Int64,1}:
 0
 1

In [86]:
sum(m)

1

In [87]:
function matching2(m_prefs,f_prefs)

    Z = zeros(m,n) 
    matched_m = [0i for i in 1:m] 
    matched_f = [0j for j in 1:n]
    
    
    for i in 1:m        #男性m人について
     
        if m_prefs[i][1] == 0　　#男性iが独身を第一志望するとき
            
            matched_m[i] = 0                    
        end
            
        if m_prefs[i][1] !== 0  #男性iが第一志望する女性がいるとき

                    
            if sum(Z[:,m_prefs[i][1]]) == 0　#男性iが第一志望する女性の列に誰もいないとき
                
                matched_m[i] = m_prefs[i][1]
                matched_f[m_prefs[i][1]] = i
                Z[i,m_prefs[i][1]] = 1.0   
            end
                
            if sum(Z[:,m_prefs[i][1]]) == 1.0 #男性iが第一志望する女性の列に誰かいるとき
                    
                if findfirst(f_prefs[m_prefs[i][1]],i) < findfirst(f_prefs[m_prefs[i][1]],size(Z[:,m_prefs[i][1]],1.0))
                #男性iが受け入れ保留されていた男性よりも女性に好まれているとき
                        
                    matched_m[i] = m_prefs[i][1]
                    matched_f[m_prefs[i][1]] = i
                    Z[i,m_prefs[i][1]] = 1.0
                    Z[size(Z[:,m_prefs[i][1]],1.0),m_prefs[i][1]] = 0.0
                    shift!(m_prefs[size(Z[:,m_prefs[i][1]],1.0)]) #受け入れ保留されていた男性の志望から第一志望を除く
                    
                end                    
                
                else #受け入れ保留されていた男性のほうが女性に好まれているとき
                    
                    shift!(m_prefs[i]) #男性iの志望から第一志望を除く
                    
                end
                
            end
        
    end

    return matched_m, matched_f

end

matching2 (generic function with 1 method)

In [ ]:
function matching(m_prefs,f_prefs)
    
    M = [i for i in 1:m]
    F = [j for j in 1:n]
    matched_m = [0i for i in 1:m]   
    matched_f = [0j for j in 1:n]
    Z = [1]
    accepted_m = pop!(Z)
    Matrix = zeros(Int64,m,n)
    
    
    while sum(accepted_m) !== m       #男性が全員安定した状況になるまで
                
                for g in 1:m
                    
                    if m_prefs[i][1] == 0       #男性gの第一志望が独身のとき
                        
                        push!(accepted_m,1)
                        
                    end
                    
                    if m_prefs[i][1] !== 0      #男性gに第一志望の女性がいるとき
                        
                        if findfirst(f_prefs[m_prefs[i][1]],i) == 0       #男性gが第一志望の女性の眼中にないとき
                            
                            shift!(m_prefs[i]) #男性iの志望から第一志望を除く
                            
                        end
                        
                        if findfirst(f_prefs[m_prefs[i][1]],i) !== 0      #男性gが第一志望の女性の選択肢に入っているとき
                        
                            if sum(Matrix[:,m_prefs[i][1]]) == 0      #第一志望の女性の列に誰もいないとき
                            
                                matched_m[i] = m_prefs[i][1]
                                matched_f[m_prefs[i][1]] = i
                                Matrix[i,m_prefs[i][1]] = i
                                push!(accepted_m,1)                      
                            
                            end
                        
                            if sum(Matrix[:,m_prefs[i][1]]) !== 0     #第一志望の女性の列に誰かいるとき
                             
                                if findfirst(f_prefs[m_prefs[i][1]],i) < findfirst(f_prefs[m_prefs[i][1]],sum(Matrix[:,m_prefs[i][1]]))
                                   #男性gが保留されていた男性よりも女性の好ましい選択であるとき
                                    
                                    matched_m[i] = m_prefs[i][1]
                                    matched_f[m_prefs[i][1]] = i
                                    Matrix[i,m_prefs[i][1]] = i
                                    shift!(m_prefs[sum(Matrix[:,m_prefs[i][1]])]) 　　#保留されていた男性の志望から第一志望を除く
                                    
                                end
                                
                                if findfirst(f_prefs[m_prefs[i][1]],i) > findfirst(f_prefs[m_prefs[i][1]],sum(Matrix[:,m_prefs[i][1]]))
                                    #保留されていた男性が男性gよりも女性の好ましい選択であるとき
                                    
                                    shift!(m_prefs[i]) #男性iの志望から第一志望を除く
                                    
                                end
                                
                            end
                            
                        end
                        
                    end
                    
                end
                
            end
            
            return matched_m, matched_f
            
        end

In [ ]:
function matching(m_prefs,f_prefs)
    
    M = [g for g in 1:m]
    F = [j for j in 1:n]
    matched_m = zeros(Int64,m) 
    matched_f = zeros(Int64,n)
    accepted_m = [0]
    Matrix = zeros(Int64,m,n)
    
    
    while sum(accepted_m) !== m       #男性が全員安定した状況になるまで
                
                for i in 1:m
                    
                    if m_prefs[i][1] == 0       #男性gの第一志望が独身のとき
                        
                        push!(accepted_m,1)     #完了済みの男性群へ
                        
                    end 
                    
                    if m_prefs[i][1] !== 0      #男性gに第一志望の女性がいるとき
                        
                        if findfirst(f_prefs[m_prefs[i][1]],i) == 0       #男性gが第一志望の女性の眼中にないとき
                            
                            shift!(m_prefs[i]) 　　#男性iの志望から第一志望を除く
                            
                        end
                        
                        if findfirst(f_prefs[m_prefs[i][1]],i) !== 0      #男性gが第一志望の女性の選択肢に入っているとき
                        
                            if sum(Matrix[:,m_prefs[i][1]]) == 0      #第一志望の女性の列に誰もいないとき
                            
                                matched_m[i] = m_prefs[i][1]
                                matched_f[m_prefs[i][1]] = i
                                Matrix[i,m_prefs[i][1]] = i
                                push!(accepted_m,1) 　　　　　　　#完了済みの男性群へ                     
                            
                            end
                        
                            if sum(Matrix[:,m_prefs[i][1]]) !== 0     #第一志望の女性の列に誰かいるとき
                             
                                if findfirst(f_prefs[m_prefs[i][1]],i) < findfirst(f_prefs[m_prefs[i][1]],sum(Matrix[:,m_prefs[i][1]]))
                                   #男性gが保留されていた男性よりも女性の好ましい選択であるとき
                                    
                                    matched_m[i] = m_prefs[i][1]
                                    matched_f[m_prefs[i][1]] = i
                                    Matrix[i,m_prefs[i][1]] = i
                                    shift!(m_prefs[sum(Matrix[:,m_prefs[i][1]])]) 　　#保留されていた男性の志望から第一志望を除く
                                    
                                end
                                
                                if findfirst(f_prefs[m_prefs[i][1]],i) > findfirst(f_prefs[m_prefs[i][1]],sum(Matrix[:,m_prefs[i][1]]))
                                    #保留されていた男性が男性gよりも女性の好ましい選択であるとき
                                    
                                    shift!(m_prefs[i]) #男性iの志望から第一志望を除く
                                    
                                end
                                
                            end
                            
                        end
                        
                    end
                    
                end
                
            end
            
            return matched_m, matched_f
            
        end

In [ ]:
Pkg.checkout("MyMatching", "master")