受入保留 (Deferred Acceptance) アルゴリズムを実装してみる。

In [1]:
m = 4
n = 3

3

In [2]:
M = [i for i in 1:m]
F = [j for j in 1:n]

3-element Array{Int64,1}:
 1
 2
 3

In [3]:
using Matching

In [4]:
function mat2vecs{T<:Integer}(prefs::Matrix{T})
    return [prefs[1:findfirst(prefs[:, j], 0)-1, j] for j in 1:size(prefs, 2)]
end

mat2vecs (generic function with 1 method)

In [5]:
m_prefs, f_prefs = mat2vecs.(random_prefs(m, n, allow_unmatched=false))

(Array{Int64,1}[[2,3,1],[3,2,1],[2,3,1],[1,3,2]],Array{Int64,1}[[1,3,4,2],[3,2,4,1],[3,4,1,2]])

In [6]:
m_prefs, f_prefs = mat2vecs.(random_prefs(m, n))

(Array{Int64,1}[[1,2,3],[2,1],[3,2,1],[1,3,2]],Array{Int64,1}[[1,3,4],[2,4],[3,4,1,2]])

In [7]:
m_prefs

4-element Array{Array{Int64,1},1}:
 [1,2,3]
 [2,1]  
 [3,2,1]
 [1,3,2]

In [8]:
f_prefs

3-element Array{Array{Int64,1},1}:
 [1,3,4]  
 [2,4]    
 [3,4,1,2]

In [14]:
S = zeros(m,n)　#受け入れ保留する組み合わせを0.0 -> 1.0とする　（unmatched がなければ rank(s)=n ??)

4×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [15]:
S

4×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [18]:
S[2,2]

0.0

In [30]:
S[:,1] == zeros(m)

true

In [31]:
S[1,:] == zeros(n)

true

In [28]:
zeros(m)

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

In [29]:
function matching (m_prefs, f_prefs)
    
    S = zeros(m,n)  B = []
    
    if m_prefs[i] == B
        
        return m_matched[i] = 0
        
    end
    
    if m_prefs[i] !== B
        
        
    
    
        if S[:,m_prefs[i]] == zeros(m)   #女性のとこに誰もいなければ
      
            return S[i,m_prefs[i]] = 1.0　
        
        end
    
        if S[:,m_prefs[i]] !== zeros(m)　　#女性のところに誰かいれば（受け入れ保留されている）
        
            if                                           #iのほうが女性に好まれているとき
        
        

LoadError: syntax: space before "(" not allowed in "matching ("

0-element Array{Any,1}

1

0-element Array{Int64,1}